import os
import time
import feedparser
from typing import Dict, List
from .hitl_governor import add_proposal

def fetch_trending_from_sans(limit: int = 5) -> List[Dict]:
    feed = feedparser.parse("https://isc.sans.edu/rssfeed.xml")
    out = []
    for e in getattr(feed, "entries", [])[:limit]:
        out.append({"title": getattr(e, "title", ""), "link": getattr(e, "link", "")})
    return out

def build_wazuh_rule_xml(title: str, link: str) -> str:
    safe_desc = (title or "Trending exploit").replace("<", "").replace(">", "")
    xml = f"""<group name="rule_evo">
  <rule id="180001" level="10">
    <description>{safe_desc} - auto-generated by RuleEvolution</description>
    <match>{safe_desc.split()[0]}</match>
  </rule>
</group>
"""
    return xml

def main():
    items = fetch_trending_from_sans()
    for it in items:
        xml = build_wazuh_rule_xml(it.get("title", ""), it.get("link", ""))
        add_proposal(
            actor="rule_evolution",
            action="inject_wazuh_rule",
            payload={"xml": xml, "source": "sans_isc", "ref": it.get("link", "")},
            reason="New exploit trend detected; propose Wazuh rule injection",
            expires_sec=3600
        )
        time.sleep(0.2)

if __name__ == "__main__":
    main()
